- name: Install NodeJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
- name: Copy backend service file
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Add application user
  ansible.builtin.user:
    name: expense

- name: Include App Pre-Requisites
  ansible.builtin.import_role:
     name: common
     taks_from: app_prereq

- name: Install NodeJS dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Install MySQL client
  ansible.builtin.dnf:
    name: mysql

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql.kdevopsb75.online -uroot -pExpenseApp@1 < /app/schema/backend.sql

- name: Start backend service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes
